# Generated by Django 3.1.6 on 2021-08-23 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scrap', models.FileField(upload_to='crap_data')),
            ],
        ),
    ]
